learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_log/learning_logs/urls.py
"""Определяет схемы url для learning_logs."""
from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # домашняя страница
    path('', views.index, name='index'),
    # страница со списком тем
    path('topics/', views.topics, name='topics'),
    # страница с подробной информацией по отдельной теме
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # страница для добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),
    # удалить тему
    path('delete_topic/<int:topic_id>', views.delete_topic, name='delete_topic'),
    # страница для добавления новой записи
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # страница для редактирования записей
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # удаление записи
    path('delete_entry/<int:delete_id>/', views.delete_entry, name='delete_entry')

]

learning_log/users/urls.py
'''Определяем схемы urls для пользователей'''
from django.urls import include, path

from . import views

app_name = 'users'
urlpatterns = [
    # включить url авторизация по умолчанию
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

learning_log/learning_logs/models.py
from django.contrib.auth.models import User
from django.db import models


class Topic(models.Model):
    """Тема которую изучает пользователь"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Возращает строковое представление модели"""
        return self.text


class Entry(models.Model):
    """Информация, изученная пользователем по теме"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) > 50:
            return f'{self.text[:50]}...'
        else:
            return self.text

learning_log/learning_logs/forms.py
from django import forms

from .models import Entry, Topic


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_log/learning_logs/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render

from .forms import EntryForm, TopicForm
from .models import Entry, Topic


def index(request):
    # домашняя страница
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Выводит список тем"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Выводит одну тему и все ее записи"""
    topic = get_object_or_404(Topic, id=topic_id)
    # проверка того, что темa принадлежит текущему пользователю
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def delete_topic(request, topic_id):
    form = Topic.objects.filter(id=topic_id).delete()
    context = {'form': form}
    return render(request, 'learning_logs/delete_topic.html', context)


@login_required
def new_topic(request):
    """Определяет новую тему."""
    if request.method != 'POST':
        # данные не отправлялись: создается пустая форма
        form = TopicForm()
    else:
        # отправленные данные 'POST': обработать данные
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    # выведет пустую или недействительную форму
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # данные не отправлялись: создается пустая форма
        form = EntryForm()
    else:
        # отправленные данные 'POST': обработать данные
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    # выведет пустую или недействительную форму
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Редактирование существущующей записи"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # проверка того, что тему принадлежит текущему пользователю
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # исходный запрос: форма заполняется данными текущей
        form = EntryForm(instance=entry)
    else:
        # отправленные данные 'POST': обработать данные
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def delete_entry(request, delete_id):
    form = Entry.objects.filter(id=delete_id).delete()
    context = {'form': form}
    return render(request, 'learning_logs/delete_entry.html', context)

learning_log/users/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render


def register(request):
    """Регестрируем нового пользователя"""
    if request.method != 'POST':
        # Выводит пустую форму
        form = UserCreationForm()
    else:
        # обработка заполненной формы
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # выполнение входа и перенаправление на домашнюю страницу
            login(request, new_user)
            return redirect('learning_logs:index')

    # вывести пустую или недействительную форму
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Learning log</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
        Learning log</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:topics'%}">
              Topics</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Registration</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

learning_log/learning_logs/templates/learning_logs/delete_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}<h3>Entry deleting</h3>{% endblock page_header %}
{% block content %}
    <a href="{% url 'learning_logs:topics' %}">Back to Topics.</a>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/delete_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}<h3>Topic deleting.</h3>{% endblock page_header %}
{% block content %}
    <a href="{% url 'learning_logs:topics' %}">Back to topics.</a>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
<h4>Topic: <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h4>

<h3>Changed topic:</h3>

{% endblock page_header %}

{% block content %}
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post" class="form">
	  {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Save changed</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">
            Keep track of your learning.</h1>
        <p class="lead">Make your learning journal and keep a list of the topics you are learning. When you learn
            something new on a topic, make a note summarizing what you have learned.</p>
        <a href="{% url 'users:register' %}" class="btn btn-lg btn-primary" role="button">Registration &raquo;</a>
    </div>
{% endblock page_header %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}

<h4>Topic: <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h4>
<h5>Adding new entry:</h5>

{% endblock page_header %}


{% block content %}
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post" class="form">
	{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}

  <h2>Adding new topics.</h2>

{% endblock page_header %}


{% block content %}
<form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
	{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry.</a>
    </p>

    <ul>
        {% for entry in entries %}
            <div class="card mb-3">
                <h4 class="card-header">
                    {{ entry.date_added|date:'M d, Y H:i'}}
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            Action
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'learning_logs:edit_entry' entry.id %}">Edit</a>
                            <div class="dropdown-divider"></div>
                            <a style="color: red;" class="dropdown-item" href="{% url 'learning_logs:delete_entry' entry.id %}">Delete</a>
                        </div>
                    </div>
                </h4>
                <div class="card-body">
                    {{ entry.text|linebreaks }}
                </div>
            </div>
            {% empty %}
            <p>There are no posts on this topic yet.</p>
        {% endfor %}
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li><h5>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                <a style="margin-left: 80%;" class="btn btn-outline-danger" href="{% url 'learning_logs:delete_topic' topic.id %}">Delete</a>
            </h5></li>
            {% empty %}
            <li><h3>Topics not yet added.</h3></li>
        {% endfor %}
    </ul>
    <h4><a href="{% url 'learning_logs:new_topic' %}">Add new topics.</a></h4>
{% endblock content %}